### ISSUE TITLE
New Realtek source

### ISSUE THREAD

**Issue by ghost** [zebulon2/rtl8812au-driver-5.2.9#1]
Hi there

I've got the new 5.2.9.3 source from a couple of days ago, and I am testing it just now, with the usual fixes for kernel 4.11, 4.11.9 and 4.12 and also the expanded device list and a small compile warning which only really came to light with a new compiler.

They have added some new features and fixes which look quite promising, but their kernel base is a few versions old, which is an annoyance. They are making changes to their old 5.2.9 rather than rebasing with a more modern kernel.

Anyways, the code, as fixed, compiles with no errors or warnings like before. If it passes muster, then I will push the changes to my repo. One thing I have noticed is the ping anomalies are a bit less, and I don't lose the signal if I go too close to the router (a weirdness with older drivers that has baffled me for some months) ... here's hoping we have a winner.

**Comment by zebulon2** [comment]
Fantastic. I just repackaged for Archlinux. Many thanks for your help with this.
