### ISSUE TITLE
Doesn't work on Kali Linux 2018.1 Kernel 4.14

### ISSUE THREAD

**Issue by alexkvazos** [zebulon2/rtl8812au-driver-5.2.9#10]
dmesg output:
![screen shot 2018-02-25 at 2 46 55 pm](https://user-images.githubusercontent.com/4448627/36646257-cdfb06ec-1a3a-11e8-8d03-18ab1520bd51.png)

**Comment by jessicuzwhynot** [comment]
Having the exact same issue, anyone found the fix for it yet?
