### ISSUE TITLE
8812au: Unknown symbol __vfs_read (err 0)

### ISSUE THREAD

**Issue by sanguinariojoe** [zebulon2/rtl8812au-driver-5.2.9#2]
Arch Linux, Kernel 4.14.r1108.g87df261-1

It seems to be related with this https://github.com/zfsonlinux/spl/issues/656, which can be solved by https://github.com/sarangnemo/anbox/commit/f633d641c21f45e46aa9585fc38389da033c0212

**Comment by ghost** [comment]
This issue has now been dealt with, with somewhat better fixes than just replacing the offending lines. It only applies to kernels >= 4.14, therefore the fixes test which kernel version and add/remove lines appropriately. That way the new code still compiles on old kernels.

**Comment by zebulon2** [comment]
Fixed with 08e0472fbc60be09f6207b21819ed141cb81d579.

**Comment by d4nuu8** [comment]
Something is wrong since my last update :

System: Arch Linux
Kernel: 4.14.6-1
Package: rtl8812au-v5-dkms-git-5.2.9-1
Error: Unknown symbol __vfs_read (error 0)

**Comment by TheChatty** [comment]
The unknown symbol error can be fixed by:
`sed -i -e "s/__vfs_read/kernel_read/" os_dep/osdep_service.c`

**Comment by ghost** [comment]
> The unknown symbol error can be fixed by:
> `sed -i -e "s/__vfs_read/kernel_read/" os_dep/osdep_service.c`

Works for me!. Thank you very much TheChatty
