### ISSUE TITLE
Version 5.2.9 doesn't work with RTL8811AU chip

### ISSUE THREAD

**Issue by etem** [zebulon2/rtl8812au-driver-5.2.9#5]
Looks like this version is not working with rtl8811au. 
Does the driver support that chip?

**Comment by gordboy** [comment]
No it only supports 8812au.

Realtek changed their original source, from which these github drivers are derived, quite some time ago.

**Comment by dachshund-digital** [comment]
Can you point to where 8812au updated driver source might be?

**Comment by etem** [comment]
@dachshund-digital [this](https://github.com/aircrack-ng/rtl8812au/tree/v5.2.20) seems to be the most recent version of 8812 driver here on Github.
