### ISSUE TITLE
two modules built for rtl8812au

### ISSUE THREAD

**Issue by hhgoten** [zebulon2/rtl8812au-driver-5.2.9#6]
Using git clone and dkms I've got two modules 
/lib/modules/4.13.0-17-lowlatency/kernel/drivers/net/wireless/rtl8812au.ko
/lib/modules/4.13.0-17-lowlatency/updates/dkms/8812au.ko

dkms status gives
§§:~/rtl8812au-driver-5.2.9$ dkms status 
rtl8812au, 5.2.9, 4.13.0-17-lowlatency, x86_64: installed

modinfo gives two different results for rtl8812au and 8812au.ko

filename:       /lib/modules/4.13.0-17-lowlatency/kernel/drivers/net/wireless/rtl8812au.ko
version:        v4.3.14_13455.20150212_BTCOEX20150128-5

 modinfo 8812au
filename:       /lib/modules/4.13.0-17-lowlatency/updates/dkms/8812au.ko
version:        v5.2.9.3_24903.20171101

in gord-rtl8812au-dkms_1.0-13_amd64.deb and in the normal  dkms.conf there is 
BUILT_MODULE_NAME[0]="8812au" 
What did I wrong by installing . My USB-Wifi stick works . But when I used newer Kernel 4.0.13-19 things got wrong after some upgrade and dkms complained . Had to go back to my older 4.0.13-17 and used sudo dpkg -i gord-rtl8812au-dkms_1.0-13_amd64.deb to make it work again. I confess, that I tried different github modules in between, so maybe tis mixed up things.
Nevertheless I like to unterstand the two modules ( above) rtl8812au.ko and 8812au.ko and how to handle this correct.
Yours sincerely hhgoten
10829 Berlin , Germany

**Comment by gordboy** [comment]
You need to choose one method only for installation. Either manually using `make install` or `dkms install`, or automatically using the deb package.

`make install` installs to /lib/modules/$(uname -r)/kernel/drivers/net/wireless/rtl8812au.ko.

`dkms install` installs to /lib/modules/$(uname -r)/updates/dkms/8812au.ko.

Installing the deb package, uses the dkms install location.

And it looks like you have 2 driver versions, 4.3.14 and 5.2.9.3. Again you must choose only one.

You can clean things up by deleting the unwanted modules from /lib/modules/$(uname r), if you installed manually.
