### ISSUE TITLE
[KDE neon; Kernel 4.13] Driver Compiles But Does Not Install

### ISSUE THREAD

**Issue by sonic2kk** [zebulon2/rtl8812au-driver-5.2.9#8]
Yesterday I updated my KDE neon system and went to bed. Today, when I got home, I booted up my computer and found that the driver stopped working. I went from Kernel 4.10 (I believe) to 4.13. I've used a few drivers I found off of GitHub over a year ago for this dongle, as it's given me headaches in the past. Most didn't work except for one, and I'd just run make, make install and modprobe -a 8812au to get it to install since I can't get dkms to install anything for me. However today when I tried that it didn't work. I'm using an 802.11g dongle right now which is not ideal.

This driver, unlike the others I tried, actually compiles. No errors with sudo make, no errors with make install; everything is like it was when I installed the driver that used to work. However my system still doesn't recognize my rtl8812au chipset dongle. A few posts I've read from around the Internet all sent me to this driver.

I could always get another dongle, but I'd like to see if I can get this one working. Any suggestions on what to try?

**Comment by giupino82** [comment]
I have the same issue. On kde neon i'm unable to work with my dongle and kernel 4.13 :(
4.10 works fine.

**Comment by gordboy** [comment]
Maybe I can help a bit here.

This driver works fine with kernels 4.13 and 4.14. I know this because I wrote the code for those kernel patches, and it has been tested extensively by many users.

First of all, the driver only supports the Realtek 8812AU chipset. That means 8814AU and 8821AU will not work.

Secondly, your device has to be in the list of known USB IDs. You can get your USB ID pair, with `lsusb`.

So if your device *is* 8812AU, but not known, you can add it. If you edit os_dep/linux/usb_intf.c, you can add your USB ID pair, at around line 161-189, by inserting another line exactly like the others.

If your device is detected, `dmesg` will show a line like

```
rtl8812au 2-2:1.0 wlxXXXXXXXXXXXXXX: renamed from wlan0
```

Also, the correct commands to install are as follows:

```
$ make
$ sudo make install
```

the `depmod -a` is already done by `sudo make install`. When you insert the device the kernel will load automatically, and you can force this with

```
$ sudo modprobe 8812au
```

So if your device is detected, that means the driver is working. Of course KDE Neon networking applet might be broken, I have no idea.

I hope that has been helpful.

**Comment by gojpdchx** [comment]
@gordboy 
The `dmesg` line in your comment may contain your wireless adapter's MAC address. You may wish to edit it for privacy / security reasons.

**Comment by hhgoten** [comment]
@gordboy 
Here you are writing : 
sudo modprobe 8812au  (without rtl... )
But in Readme is: 
sudo dkms install -m rtl8812au -v 5.2.9 
 
So , what should be the name of the module:  8812au or rtl8812au ??
(you may read my open issue from Dec/17/2017 too)

**Comment by gordboy** [comment]
@hhgoten 

Both are correct.

The dkms name is rtl8812au, which is derived from the location of the source in /usr/src/rtl8812au-5.2.20. 

The final built module name for modprobe is 8812au, which is derived from the Makefile and dkms.conf.

This has been thoroughly tested. There is no error or confusion, except on your part.

**Comment by gordboy** [comment]
@gojpdchx 

Thanks for that. Now edited.

**Comment by giupino82** [comment]
@gordboy tried to recompile after inserting my USB ID.
dongle seems rercognized: 

> rtl8812au 1-1.3:1.0 wlxxxxxxxx: renamed from wlan0

is showed but link seems DOWN.
ip link set _interface_ up show:

> RTNETLINK answers: Operation not permitted

Btw, the driver seems to work... this should be a KDE neon issue.
Tnx

edit: ok. My fault here, i was quite sure i was on rtl8812AU that's wrong, i'm on rtl8811AU.
i tried various ver of driver but atm no one work on kernel 4.13 under KDE Neon.
this ver works on Arch and kernel 4.14 [here](https://github.com/zebulon2/rtl8812au/tree/v5.1.5)

edit2: finally ver 5.1.5 works also on kde neon. I had to delete previous created 8812au.ko from kernel headers.
Sorry for confusion :)

**Comment by gordboy** [comment]
@giupino82 glad you are now working.

When you update to kernel 4.15 in the April distro upgrades, you might need to upgrade your driver also. I'm not sure if your driver goes up to kernel 4.15. I know my new one does, but it does not cover your chipset.

See what happens is Realtek release drivers that are out of date, and here on github we perpetually patch them to fit the newer kernels. It is a lot of work. There are at least 6 different versions of the driver, each covering different combinations of chipsets, and countless kernel variations also.

Consequently there are literally hundreds of drivers here, all essentially the same, but different enough not to work for all possible permutations and combinations.

**Comment by magudelo58** [comment]
Hello,

I got an upgrade for 4.15.0-10-generic and the driver stopped working. I tried recompiling the current version from https://github.com/gordboy/rtl8812au but neither the following steps restored the driver:

Manual install:
- make clean
- make
- sudo make install
- sudo modprobe 8812au

Or by using the DKMS install:
- sudo dkms add -m rtl8812au -v 5.2.20
- sudo dkms build -m rtl8812au -v 5.2.20
- sudo dkms install -m rtl8812au -v 5.2.20

Not sure if this is related, but dkms is giving me a warning reporting some differences between the built and installed module:
sudo dkms status
8192cu, 1.10, 4.13.0-25-generic, i686: installed
rtl8812au, 5.2.20, 4.15.0-10-generic, i686: installed (WARNING! Diff between built and installed module!)

modinfo 8812au | grep -i version:
version:        v5.2.20_25672.20171213
srcversion:     1EB8049672BECCCABE2CFF6
parm:           rtw_chip_version:int

This is the output from DMESG after removing and reinserting the 802.11N dongle :
[ 3070.210655] usbcore: deregistering interface driver rtl8812au
[ 3760.441749] usb 1-3: USB disconnect, device number 6
[ 3794.740082] usb 1-3: new high-speed USB device number 7 using ehci-pci
[ 3794.897147] usb 1-3: New USB device found, idVendor=7392, idProduct=a812
[ 3794.897157] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 3794.897162] usb 1-3: Product: Edimax AC600 USB
[ 3794.897167] usb 1-3: Manufacturer: Realtek
[ 3794.897171] usb 1-3: SerialNumber: 00e04c000001

**Comment by magudelo58** [comment]
@gordboy
Never mind: found another driver under https://github.com/abperiasamy/rtl8812AU_8821AU_linux which is working in 4.15.0.10.

Thank you
